public record Project(String name,
                      String description,
                      int javaVersion,
                      String authorName,
                      String mvnGroup,
                      String mvnArtifact,
                      String license) {

    public static String[] LICENSES = {
            "GPL-2.0",
            "GPL-3.0",
            "AFL-3.0",
            "MIT",
            "Apache-2.0",
            "AGPL-3.0",
            "LGPL-2.1",
            "LGPL-3.0",
            "Artistic-2.0",
            "BSL-1.0",
            "BSD-2-Clause",
            "BSD-3-Clause",
            "BSD-3-Clause-Clear",
            "BSD-4-Clause",
            "0BSD",
            "CC",
            "CC0-1.0",
            "CC-BY-4.0",
            "CC-BY-SA-4.0",
            "WTFPL",
            "ECL-2.0",
            "EPL-1.0",
            "EUPL-1.1",
            "ISC",
            "LPPL-1.3c",
            "MS-PL",
            "MPL-2.0",
            "OSL-3.0",
            "PostgreSQL",
            "OFL-1.1",
            "NCSA",
            "Unlicense",
            "Zlib",
    };
}
